### ISSUE TITLE
Setup LLama 3.1 and have a test script to run it locally

### ISSUE THREAD

**Issue by keval-b** [keval-b/Daily_LLM_Learnings#1]
###Story
Set-up Llama 3.1 smaller model (7B) and figure out chatting with it locally.

Requirements
Ollama local set-up

###Tasks

- [ ]  Ollama Set-up
- [ ]  3.1 Llama model download
- [ ] Resource search for building a terminal based chatbot on top
- [ ] Use streamlit to make it browser based

###Libraries
Ollama, Streamlit
